import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

const distDir = path.join(root, 'dist');
fs.mkdirSync(distDir, { recursive: true });

const source = fs.readFileSync(path.join(root, 'src/index.js'), 'utf8');
const banner = '// Build artifact generated by scripts/build.mjs\n';
fs.writeFileSync(path.join(distDir, 'index.js'), banner + source);

console.log('Build completed: dist/index.js');
